version: '3.8'
services:
   tunnel-proxy:
    env_file:
      - ./.env
    image: esrrhs/pingtunnel
    container_name: pingtunnel-proxy
    restart: always
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    command: [
      "./pingtunnel",
      "-type", "client",
      "-l", ":${PROXY_PORT}",
      "-s", "${SERVER_ADDRESS}",
      "-t", "${SERVER_ADDRESS}:${PROXY_PORT}",
      "-tcp", "1",
      "-key", "${PASSWORD}"
    ]
   tunnel-openvpn:
    env_file:
      - ./.env
    image: esrrhs/pingtunnel
    container_name: pingtunnel-ovpn
    restart: always
    ports:
      - "${OVPN_PORT}:${OVPN_PORT}"
    command: [
      "./pingtunnel",
      "-type", "client",
      "-l", ":${OVPN_PORT}",
      "-s", "${SERVER_ADDRESS}",
      "-t", "${SERVER_ADDRESS}:${OVPN_PORT}",
      "-tcp", "1",
      "-key", "${PASSWORD}"
    ]
   tunnel-openvpn-udp:
    env_file:
      - ./.env
    image: esrrhs/pingtunnel
    container_name: pingtunnel-ovpn-udp
    restart: always
    ports:
      - "${OVPN_PORT}:${OVPN_PORT}/udp"
    command: [
      "./pingtunnel",
      "-type", "client",
      "-l", ":${OVPN_PORT}",
      "-s", "${SERVER_ADDRESS}",
      "-t", "${SERVER_ADDRESS}:${OVPN_PORT}",
      "-key", "${PASSWORD}"
    ]
