version: '3.8'

services:
  tinyproxy:
    env_file:
      - ./.env
    image: vimagick/tinyproxy
    build:
      context: ./tinyproxy
      args:
        PROXY_USER: "${PROXY_USER}"
        PROXY_PASS: "${PROXY_PASS}"
    ports:
      - "${PROXY_PORT}:8888"
    restart: unless-stopped

  openvpn-tcp:
    env_file:
      - ./.env
    build:
      context: ./ovpn
      args:
        OVPN_URL: "tcp://${OVPN_TCP_SERVER_ADDRESS}"
        OVPN_PORT: "${OVPN_PORT}"
    container_name: openvpn-tcp
    cap_add:
      - NET_ADMIN
    ports:
      - "${OVPN_PORT}:1194/tcp"
    volumes:
      - ./openvpn-tcp-data:/etc/openvpn
    environment:
      - TZ=UTC
    restart: unless-stopped

  openvpn-udp:
    env_file:
      - ./.env
    build:
      context: ./ovpn
      args:
        OVPN_URL: "udp://${OVPN_UDP_SERVER_ADDRESS}"
        OVPN_PORT: "${OVPN_PORT}"
    ports:
      - "${OVPN_PORT}:1194/udp"
    container_name: openvpn-udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn-udp-data:/etc/openvpn
    environment:
      - TZ=UTC
    restart: unless-stopped

  pingtunnel-server:
    image: esrrhs/pingtunnel
    container_name: pingtunnel-server
    privileged: true
    network_mode: host
    restart: always
    command: ["./pingtunnel", "-type", "server", "-key", "${PASSWORD}"]
